#nullable enable
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Text;

[Generator]
public class MongoOptionsDiscoveryGenerator : IIncrementalGenerator
{
    public class ClassInfo
    {
        public string ClassName { get; set; } = string.Empty;
        public string? OptionsName { get; set; }
        public string? OptionsFullName { get; set; }
        public string FullName { get; set; } = string.Empty;
        public bool IsValidatorClass { get; set; }
        public bool IsMongoOptions { get; set; }
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        //Debugger.Launch();
        // 1. Find classes with [MongoOptions] attribute
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (ctx, _) => GetClassSymbol(ctx))
            .Where(static m => m is not null);
        
        var values = context.AnalyzerConfigOptionsProvider.Select((options, _) =>
        {
            // Try to get the RootNamespace of the project currently being compiled
            options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);
            return rootNamespace ?? "DefaultName";
        });

        var newProvider = provider.Combine(values);
        
        context.RegisterSourceOutput(newProvider.Collect(), Execute);
    }

    private static ClassInfo? GetClassSymbol(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);

        if (symbol == null) return null;
        // We look for any attribute named "MongoOptions"
        var sym = symbol.GetAttributes().Any(a => a.AttributeClass?.Name == "MongoOptionAttribute");
        var validator = symbol.GetAttributes().Any(a => a.AttributeClass?.Name == "OptionsValidatorAttribute");

        if (!sym && !validator) return null;

        var classInfo = new ClassInfo
        {
            IsValidatorClass = validator,
            IsMongoOptions = sym,
            ClassName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            FullName = symbol.Name
        };

        if (validator)
        {
            var validationInterface = ((INamedTypeSymbol)symbol).AllInterfaces.FirstOrDefault(i =>
                i.IsGenericType &&
                i.ConstructedFrom.ToDisplayString().StartsWith("Microsoft.Extensions.Options.IValidateOptions"));

            if (validationInterface != null)
            {
                // 3. Get the 'T' (e.g., MongoThemeOptions)
                //ITypeSymbol genericType = validationInterface.TypeArguments[0];
                if (validationInterface is { TypeArguments.Length: > 0 })
                {
                    var genericType = validationInterface.TypeArguments[0];
                    // Proceed with logic...

                    // 4. Use the name for your logic
                    classInfo.OptionsName = genericType.Name; // "MongoThemeOptions"
                    classInfo.OptionsFullName = genericType.ToDisplayString(); // "YourApp.Models.MongoThemeOptions"
                }
            }
        }

        return classInfo;
    }

    private void Execute(SourceProductionContext context, ImmutableArray<(ClassInfo? Left, string Right)> array)
    {
        if (array.Length <= 0) return;
        var rootNameSpace = array[0].Right;
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using MongoOptions.Services;");
        sb.AppendLine("using MongoOptions.Extensions;");
        sb.AppendLine("using Microsoft.Extensions.Options;");
        sb.AppendLine($"namespace {rootNameSpace};");
        sb.AppendLine("public static partial class MongoOptionsExtensions {");
        sb.AppendLine("    public static MongoOptionsBuilder RegisterDiscoveredOptions(this MongoOptionsBuilder builder) {");

        foreach (var className in array)
        {
            if (className.Left == null) continue;
            var info = className.Left;
            if (info.IsMongoOptions)
            {
                AppendWithIndent(sb, $"builder.RegisterOptions<{className.Left.ClassName}>();", 8);
            }
            if (info.IsValidatorClass)
            {
                AppendWithIndent(sb, $"builder.Services.AddSingleton<IValidateOptions<global::{className.Left.OptionsFullName}>, {className.Left.ClassName}>();", 8);
            }
        }

        AppendWithIndent(sb, "return builder;", 8);
        AppendWithIndent(sb, "}", 4);
        AppendWithIndent(sb, "public static IServiceCollection AddDiscoveredOptions(this IServiceCollection services) {", 4);
        foreach (var className in array)
        {
            if (className.Left == null) continue;
            var info = className.Left;
            if (info.IsMongoOptions)
            {
                AppendWithIndent(sb, $"services.AddMongoOptions<{className.Left.ClassName}>();", 8);
            }
            if (info.IsValidatorClass)
            {
                AppendWithIndent(sb, $"services.AddSingleton<IValidateOptions<global::{className.Left.OptionsFullName}>, {className.Left.ClassName}>();", 8);
            }
        }
        AppendWithIndent(sb, "return services;", 8);
        AppendWithIndent(sb, "}", 4);
        sb.AppendLine("}");

        context.AddSource("MongoOptionsDiscovery.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private StringBuilder AppendWithIndent(StringBuilder sb, string Value ,int indent)
    {
        sb.Append(' ', indent);
        sb.Append(Value + "\n");
        return sb;
    }
}