using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Xml.Schema;

[Generator]
public class MongoOptionsDiscoveryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Find classes with [MongoOptions] attribute
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (ctx, _) => GetClassSymbol(ctx))
            .Where(static m => m is not null);
        
        var values = context.AnalyzerConfigOptionsProvider.Select((options, _) =>
        {
            // Try to get the RootNamespace of the project currently being compiled
            options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);
            return rootNamespace ?? "DefaultName";
        });

        var newProvider = provider.Combine(values);
        
        // 2. Generate the discovery code
        context.RegisterSourceOutput(newProvider.Collect(), Execute);
    }

    private static string? GetClassSymbol(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);

        // We look for any attribute named "MongoOptions"
        return symbol?.GetAttributes().Any(a => a.AttributeClass?.Name == "MongoOptionsAttribute") == true
               ? symbol.ToDisplayString() : null;
    }

    private void Execute(SourceProductionContext context, ImmutableArray<(string Left, string Right)> array)
    {
        var rootNameSpace = array[0].Right;
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using MongoOptions;");
        sb.AppendLine("using MongoOptions.Extensions;");
        sb.AppendLine($"namespace {rootNameSpace};");
        sb.AppendLine("public static partial class MongoOptionsExtensions {");
        sb.AppendLine("    public static MongoOptionsBuilder RegisterDiscoveredOptions(this MongoOptionsBuilder builder) {");

        foreach (var className in array)
        {
            AppendWithIndent(sb, $"builder.RegisterOptions<{className.Left}>();", 8);
        }

        AppendWithIndent(sb, "return builder;", 8);
        AppendWithIndent(sb, "}", 4);
        AppendWithIndent(sb, "public static IServiceCollection AddDiscoveredOptions(this IServiceCollection services) {", 4);
        foreach (var className in array)
        {
            AppendWithIndent(sb, $"services.AddMongoOptions<{className.Left}>();", 8);
        }
        AppendWithIndent(sb, "return services;", 8);
        AppendWithIndent(sb, "}", 4);
        sb.AppendLine("}");

        context.AddSource("MongoOptionsDiscovery.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private StringBuilder AppendWithIndent(StringBuilder sb, string Value ,int indent)
    {
        sb.Append(' ', indent);
        sb.Append(Value + "\n");
        return sb;
    }
}